---

- name: Add mono's apt key from keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"

- name: Add mono's repository to software list
  apt_repository:
    repo: "deb http://download.mono-project.com/repo/debian jessie main"
    update_cache: yes

- name: Install all prerequisites for Radarr
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - mono-devel 
   - mediainfo 
   - sqlite3
   - libmono-cil-dev

- name: Create the Radarr user and group
  user: 
    name: "{{ radarr_user }}"
    comment: "Radarr user"

- name: Download Radarr tar file. Version "{{ radarr_version }}"
  get_url:
    url: "https://github.com/Radarr/Radarr/releases/download/v{{ radarr_version }}/Radarr.develop.{{ radarr_version }}.linux.tar.gz"
    dest: "/tmp"

- name: Unzip the radarr zip file
  unarchive:
    src: "/tmp/Radarr.develop.{{ radarr_version }}.linux.tar.gz"
    dest: "/opt"

- name: Change persmissions on the Radarr
  file:
    path: "{{ radarr_dest }}"
    state: directory
    mode: 0644
    owner: "{{ radarr_user }}"

- name: Copy the service file
  template:
    src: "radarr.service.j2"
    dest: "/etc/systemd/system/radarr.service"
    owner: "{{ sonarr_user }}"
    mode: 0644