---
# tasks file for ansible-role-radarr

- include: debian.yml
  when:
    ansible_os_family == "Debian"
- include: redhat.yml
  when:
    ansible_os_family == "RedHat"

- name: Start and enable the Radarr service
  service:
    name: "radarr"
    state: started
    enabled: yes
